AWSTemplateFormatVersion: "2010-09-09"
Description: AWS SAM template for the Test::Test::Test resource type
Resources:
  TestEntrypoint:
    Metadata: &id001
      BuildProperties:
        UseNpmCi: true
    Properties:
      CodeUri: ./
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs18.x
      Environment:
        Variables:
          NODE_ENV: dev
    Type: AWS::Serverless::Function
  TypeFunction:
    Metadata: *id001
    Properties:
      CodeUri: ./
      Handler: dist/handlers.entrypoint
      Runtime: nodejs18.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
