AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template for the Test::Test::Test resource type
Resources:
  TestEndpoint:
    Metadata: &id001
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - src/handlers.ts
        External:
        - '@aws-sdk/*'
        - p-retry
        - piscina
        Format: esm
        Sourcemap: 'true'
        Target: es2022
    Properties:
      CodeUri: ./
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs18.x
    Type: AWS::Serverless::Function
  TypeFunction:
    Metadata: *id001
    Properties:
      CodeUri: ./
      Handler: dist/handlers.entrypoint
      Runtime: nodejs18.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
